FROM python:3.8

WORKDIR /app

RUN pip install --upgrade pip

COPY requirements-streamlit.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY app.py app.py

RUN mkdir -p /app/savedimage
RUN mkdir -p /app/savedimage/xray

EXPOSE 8502

CMD streamlit run app.py --server.port 8502 