#!/usr/bin/env fish
python Effusion_model_densenet.py 
sleep 20
python Effusion_model_inception.py 
sleep 20
python Effusion_model_ResNet.py 
sleep 20
python Effusion_model_self.py 
sleep 20
python Effusion_model_vgg.py                   